<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="LAPTOP-79C88I1L" failures="4" tests="13" name="RetryMultiple" time="0.088" errors="0" timestamp="2022-05-22T17:14:30 IST">
  <testcase classname="com.vtiger.practice.TestNGRetryAnalyserTest" name="practiceTest" time="0.009">
    <skipped/>
  </testcase> <!-- practiceTest -->
  <testcase classname="com.vtiger.practice.TestNGRetryAnalyserTest" name="practiceTest" time="0.001">
    <skipped/>
  </testcase> <!-- practiceTest -->
  <testcase classname="com.vtiger.practice.TestNGRetryAnalyserTest" name="practiceTest" time="0.001">
    <skipped/>
  </testcase> <!-- practiceTest -->
  <testcase classname="com.vtiger.practice.TestNGRetryAnalyserTest" name="practiceTest" time="0.001">
    <skipped/>
  </testcase> <!-- practiceTest -->
  <testcase classname="com.vtiger.practice.TestNGRetryAnalyserTest" name="practiceTest" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [123] but found [abc]">
      <![CDATA[java.lang.AssertionError: expected [123] but found [abc]
at com.vtiger.practice.TestNGRetryAnalyserTest.practiceTest(TestNGRetryAnalyserTest.java:12)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- practiceTest -->
  <testcase classname="com.vtiger.practice.TestNGRetryAnalyserTest" name="practiceTest3" time="0.001">
    <skipped/>
  </testcase> <!-- practiceTest3 -->
  <testcase classname="com.vtiger.practice.TestNGRetryAnalyserTest" name="practiceTest3" time="0.001">
    <skipped/>
  </testcase> <!-- practiceTest3 -->
  <testcase classname="com.vtiger.practice.TestNGRetryAnalyserTest" name="practiceTest3" time="0.001">
    <skipped/>
  </testcase> <!-- practiceTest3 -->
  <testcase classname="com.vtiger.practice.TestNGRetryAnalyserTest" name="practiceTest3" time="0.001">
    <skipped/>
  </testcase> <!-- practiceTest3 -->
  <testcase classname="com.vtiger.practice.TestNGRetryAnalyserTest" name="practiceTest3" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [C] but found [A]">
      <![CDATA[java.lang.AssertionError: expected [C] but found [A]
at com.vtiger.practice.TestNGRetryAnalyserTest.practiceTest3(TestNGRetryAnalyserTest.java:25)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- practiceTest3 -->
  <testcase classname="com.vtiger.practice.TestNGRetryAnalyserTest" name="practiceTest3" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [C] but found [A]">
      <![CDATA[java.lang.AssertionError: expected [C] but found [A]
at com.vtiger.practice.TestNGRetryAnalyserTest.practiceTest3(TestNGRetryAnalyserTest.java:25)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- practiceTest3 -->
  <testcase classname="com.vtiger.practice.TestNGRetryAnalyserTest" name="practiceTest3" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [C] but found [A]">
      <![CDATA[java.lang.AssertionError: expected [C] but found [A]
at com.vtiger.practice.TestNGRetryAnalyserTest.practiceTest3(TestNGRetryAnalyserTest.java:25)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- practiceTest3 -->
  <testcase classname="com.vtiger.practice.TestNGRetryAnalyserTest" name="practiceTest2" time="0.0">
    <skipped/>
  </testcase> <!-- practiceTest2 -->
  <testcase classname="com.vtiger.practice.TestNGRetryAnalyserTest" name="practiceTest4" time="0.0">
    <ignored/>
  </testcase> <!-- practiceTest4 -->
</testsuite> <!-- RetryMultiple -->
